# Generated by Django 3.2.8 on 2023-11-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresapersona',
            name='motivos_reporte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
